### ISSUE TITLE
Generate edge and global features

### ISSUE THREAD

**Issue by gooaah** [orausch/graphrnn#8]
Hey,

Thanks so much for the new implmentation of GraphRNN! I have run the example script successfully. I am working on generation of crystal based on the graph representation. For crystal, global features for unit cell and edge features for bonds are needed. Can this model generate such features of graph? If so, how to use it? If not, how can I modify the code to implement it?

Thanks!

**Comment by orausch** [comment]
Hey, 
generating features is a bit tricky, and the authors propose a method in appendix A.6, although their method does not actually randomly sample the features beyond generating them as an output of the NN. I haven't tried nor implemented this, and I'm not aware of other papers that do this differently. Depending on your features, I think an interesting approach would be to learn parameters of a distribution (e.g. normal distribution) and then sample those distributions at inference time.

**Comment by gooaah** [comment]
> Hey, generating features is a bit tricky, and the authors propose a method in appendix A.6, although their method does not actually randomly sample the features beyond generating them as an output of the NN. I haven't tried nor implemented this, and I'm not aware of other papers that do this differently. Depending on your features, I think an interesting approach would be to learn parameters of a distribution (e.g. normal distribution) and then sample those distributions at inference time.

Greatly thanks for your reply!
